### ISSUE TITLE
ribiosCon generates invalid connection string

### ISSUE THREAD

**Issue by julianesiebourg** [bedapub/ribiosAnnotation#5]
Hello!
When using `ribiosAnnotation::humanUniqOrtholog(ids)`

In `ribiosCon`, I'm getting some weird string for the connection:

str <- ribiosAnnotation:::jdbcConnectString(user, password, connection$host, connection$port, connection$service_name)
> str
[1] "jdbc:oracle:thin:/@:/"
> con <- DBI::dbConnect(drv, str)
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLRecoverableException: IO Error: Invalid connection string format, a valid format is: "//host[:port][/service_name]" 
  
Interestingly this only happens when running ribiosAnnotation from a container.
Parameters for the `jdbcConnectString()` function (user, password, etc...) are all NULL in this case, but I don't know why.

**Comment by julianesiebourg** [comment]
This seems to happen because we don't use `ROracle` in the container. (As it's not a dependency of the package. It's not installed into the container... and it actually seems not straight forward to install ;) ).

Then `querydbSelectIn` chooses the non - ROracle option via `ribiosCon`.

**Comment by Accio** [comment]
now the issue is solved - using mongodb instead
